[package]
name = "diosbinario/brickbattle-weapons"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
reflex = "littensy/reflex@4.3.1"
immut = "solarhorizon/immut@0.4.4"
